<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ROOT</string>
	</array>
	<key>name</key>
	<string>Isabelle ROOT</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(chapter|session|in|description|options|global_theories|theories|files|document_files|sessions)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(browser_info|condition|document|document_graph|document_output|document_variants|eta_contract|goals_limit|names_long|names_short|names_unique|pretty_margin|print_mode|show_brackets|show_consts|show_main_goal|show_question_marks|show_sorts|show_types|thy_output_break|thy_output_display|thy_output_indent|thy_output_modes|thy_output_quotes|thy_output_source|timeout|global)\b</string>
			<key>name</key>
			<string>keyword.other.option</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.option</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(quick_and_dirty|skip_proofs)[ ]*(\=)[ ]*(false)\b</string>
			<key>name</key>
			<string>meta.abandon-proof.false</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(quick_and_dirty|skip_proofs)\b</string>
			<key>name</key>
			<string>invalid.illegal.abandon-proof</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{\*</string>
			<key>end</key>
			<string>\*\}</string>
			<key>name</key>
			<string>comment.block.documentation</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)|\[|\]|\=|\+|\,</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\??'?([^\W\d]|\\&lt;\w+\&gt;)([.\w\']|\\&lt;\w+\&gt;)*</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9]+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.isabelle.root</string>
	<key>uuid</key>
	<string>D9EB4C04-5E72-4D19-A640-4035F9A762C8</string>
</dict>
</plist>
